auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # rook
  k8s.gcr.io/sig-storage/csi-attacher: weilk/csi-attacher
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: weilk/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-provisioner: weilk/csi-provisioner
  k8s.gcr.io/sig-storage/csi-resizer:v1.4.0: weilk/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1: weilk/csi-snapshotter
  quay.io/ceph/ceph: weilk/ceph
  quay.io/cephcsi/cephcsi: weilk/cephcsi
  quay.io/csiaddons/k8s-sidecar: weilk/k8s-sidecar
  quay.io/csiaddons/volumereplication-operator: weilk/volumereplication-operator
  rook/ceph:v1.8.6: weilk/rook.ceph
  # tools
  k8s.gcr.io/metrics-server/metrics-server: weilk/metrics-server
  k8s.gcr.io/ingress-nginx/controller: weilk/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: weilk/git-sync
  gcr.io/kaniko-project/executor:debug,latest: weilk/kaniko-executor
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: weilk/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: weilk/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: weilk/prometheus-adapter
  # kubernetes
  k8s.gcr.io/kube-apiserver: weilk/kube-apiserver
  k8s.gcr.io/kube-controller-manager: weilk/kube-controller-manager
  k8s.gcr.io/kube-scheduler: weilk/kube-scheduler
  k8s.gcr.io/kube-proxy: weilk/kube-proxy
  k8s.gcr.io/pause: weilk/pause
  k8s.gcr.io/etcd: weilk/etcd
  coredns/coredns: weilk/coredns
